swagger: '2.0'
info:
  title: API для сервиса подписок Pay2U (проект Яндекс Практикум, Хакатон)
  version: 1.0.0
paths:
  /auth:
    post:
      summary: Авторизация пользователя
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Авторизация пройдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Авторизация не пройдена
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Ошибка авторизации
  /main:
    get:
      summary: Перейти на главный экран подписок
      tags:
        - Main
      responses:
        '200':
          description: Информация о главном экране получена
          content:
            application/json:
              schema:
                type: object
                properties:
                  availableSubscriptions:
                    type: array
                    items:
                      $ref: '#/components/schemas/SubscriptionService'
                  activeSubscriptions:
                    type: array
                    items:
                      $ref: '#/components/schemas/SubscriptionService'
                  user:
                    $ref: '#/components/schemas/User'
  /subscriptions/add:
    post:
      summary: Добавить активную подписку пользователя
      tags:
        - Subscriptions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                subscriptionServiceId:
                  type: string
                  description: ID сервиса-подписки
      responses:
        '200':
          description: Подписка добавлена
          content:
            application/json:
              schema:
                type: object
                properties:
                  subscription:
                    $ref: '#/components/schemas/SubscriptionService'
        '400':
          description: Ошибка добавления подписки
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Ошибка добавления подписки
  /subscriptions/search:
    get:
      summary: Поиск доступных сервисов
      tags:
        - Subscriptions
      parameters:
        - name: searchQuery
          in: query
          required: false
          type: string
          description: Текст поиска
        - name: categoryId
          in: query
          required: false
          type: string
          description: ID категории
      responses:
        '200':
          description: Список сервисов найден
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SubscriptionService'
  /subscriptions/categories/{categoryId}:
    get:
      summary: Получить список сервисов по категории
      tags:
        - Subscriptions
      parameters:
        - name: categoryId
          in: path
          required: true
          type: string
          description: ID категории
      responses:
        '200':
          description: Список сервисов получен
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SubscriptionService'
  /subscriptions/{subscriptionId}:
    get:
      summary: Получить описание сервиса-подписки
      tags:
        - Subscriptions
      parameters:
        - name: subscriptionId
          in: path
          required: true
          type: string
          description: ID сервиса-подписки
      responses:
        '200':
          description: Описание сервиса получено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionService'
  /subscriptions/my:
  get:
    summary: Получить список моих подписок
    tags:
      - Subscriptions
    responses:
      '200':
        description: Список подписок получен
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/SubscriptionService'
  /subscriptions/my/add:
    post:
      summary: Добавить активную подписку
      tags:
        - Subscriptions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                subscriptionServiceId:
                  type: string
                  description: ID сервиса-подписки
      responses:
        '200':
          description: Подписка добавлена
          content:
            application/json:
              schema:
                type: object
                properties:
                  subscription:
                    $ref: '#/components/schemas/SubscriptionService'
        '400':
          description: Ошибка добавления подписки
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Описание ошибки
  /subscriptions/my/{subscriptionId}/disable:
    post:
      summary: Отключить активную подписку
      tags:
        - Subscriptions
      parameters:
        - name: subscriptionId
          in: path
          required: true
          type: string
          description: ID сервиса-подписки
      responses:
        '200':
          description: Подписка отключена
          content:
            application/json:
              schema:
                type: object
                properties:
                  subscription:
                    $ref: '#/components/schemas/SubscriptionService'
        '400':
          description: Ошибка отключения подписки
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Описание ошибки
  /subscriptions/my/{subscriptionId}/details:
    get:
      summary: Получить детальную информацию о подписке
      tags:
        - Subscriptions
      parameters:
        - name: subscriptionId
          in: path
          required: true
          type: string
          description: ID сервиса-подписки
      responses:
        '200':
          description: Детальная информация о подписке получена
  /subscriptions/{subscriptionId}/payments:
    post:
      summary: Оплатить подписку
      tags:
        - Subscriptions
      parameters:
        - name: subscriptionId
          in: path
          required: true
          type: string
          description: ID сервиса-подписки
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                paymentMethod:
                  type: string
                  description: Способ оплаты
      responses:
        '200':
          description: Оплата прошла успешно
          content:
            application/json:
              schema:
                type: object
                properties:
                  receipt:
                    type: string
                    description: Чек об оплате
        '400':
          description: Ошибка оплаты
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Описание ошибки
  /subscriptions/terms:
    get:
      summary: Получить условия сервиса
      tags:
        - Subscriptions
      responses:
        '200':
          description: Условия сервиса получены
          content:
            text/plain:
              schema:
                type: string
  /subscriptions/privacy:
    get:
      summary: Получить политику обработки данных
      tags:
        - Subscriptions
      responses:
        '200':
          description: Политика обработки данных получена
          content:
            text/plain:
              schema:
                type: string
  /subscriptions/{subscriptionId}/payments/{paymentId}/receipts/export:
    post:
      summary: Экспортировать чек об оплате
      tags:
        - Subscriptions
      parameters:
        - name: subscriptionId
          in: path
          required: true
          type: string
          description: ID сервиса-подписки
        - name: paymentId
          in: path
          required: true
          type: string
          description: ID оплаты
      responses:
        '200':
          description: Чек об оплате экспортирован
          content:
            application/octet-stream:
              schema:
                type: string
        '400':
          description: Ошибка экспорта чека
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Описание ошибки
  /subscriptions/payments/default:
    put:
      summary: Сменить способ оплаты по умолчанию
      tags:
        - Subscriptions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                paymentMethodId:
                  type: string
                  description: ID нового способа оплаты по умолчанию
      responses:
        '200':
          description: Способ оплаты по умолчанию изменен
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Операция прошла успешно
        '400':
          description: Ошибка изменения способа оплаты
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Описание ошибки
  /subscriptions/user/filtered:
    get:
      summary: Получить отфильтрованный и отсортированный список подписок пользователя
      tags:
        - Subscriptions
      parameters:
        - name: filters:
          in: query
          type: object
          properties:
            category:
              type: string
              description: Категория подписки
            cost:
              type: number
              description: Стоимость подписки
      responses:
        '200':
          description: Отфильтрованный и отсортированный список подписок получен
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SubscriptionService'
  /subscriptions/user/calendar:
    get:
      summary: Получить календарь платежей пользователя
      tags:
        - Subscriptions
      responses:
        '200':
          description: Календарь платежей получен
          content:
            application/json:
              schema:
                type: object
                properties:
                  payments:
                    type: array
                    items:
                      $ref: '#/components/schemas/SubscriptionPayment'
                  upcomingPayments:
                    type: array
                    items:
                      $ref: '#/components/schemas/SubscriptionPayment'
  /subscriptions/user/calendar/{date}:
    get:
      summary: Получить информацию по выбранному дню списания
      tags:
        - Subscriptions
      parameters:
        - name: date:
          in: path
          required: true
          type: string
          format: date
          description: Дата списания
      responses:
        '200':
          description: Информация по дню списания получена
          content:
            application/json:
              schema:
                type: object
                properties:
                  payments:
                    type: array
                    items:
                      $ref: '#/components/schemas/SubscriptionPayment'
  /subscriptions/user/history:
    get:
      summary: Получить историю платежей пользователя
      tags:
        - Subscriptions
      responses:
        '200':
          description: История платежей получена
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PaymentHistory'
  /subscriptions/user/history/analytics:
    get:
      summary: Получить краткую аналитику истории платежей пользователя
      tags:
        - Subscriptions
      parameters:
        - name: month:
          in: query
          required: true
          type: string
          format: date
          description: Месяц, за который требуется аналитика
      responses:
        '200':
          description: Краткая аналитика истории платежей получена
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalSpent:
                    type: number
                    description: Общая сумма затрат
                  averagePayment:
                    type: number
                    description: Средняя сумма платежа
                  mostUsedCategories:
                    type: array
                    items:
                      type: string
                      description: Название категории
  /faq:
    get:
      summary: Получить список часто задаваемых вопросов
      tags:
        - FAQ
      responses:
        '200':
          description: Список FAQ получен
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FAQ'
  /faq/search:
    get:
      summary: Найти подходящий вопрос в FAQ
      tags:
        - FAQ
      parameters:
        - name: query:
          in: query
          required: true
          type: string
          description: Текст запроса
      responses:
        '200':
          description: Список подходящих вопросов получен
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FAQ'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          description: "ID пользователя"
        fullName:
          type: string
          description: "ФИО пользователя"
        phone:
          type: string
          description: "Телефон пользователя"
        email:
          type: string
          description: "Почта пользователя"
        login:
          type: string
          description: "Логин пользователя"
    Guide:
      type: object
      properties:
        id:
          type: string
          description: "ID гайда"
        status:
          type: string
          description: "Статус гайда"
          $ref: '#/components/schemas/GuideStatus'
        description:
          type: string
          description: "Описание гайда"
        steps:
          type: array
          items:
            type: string
            description: "Шаги гайда"
    GuideStatus:
      type: object
      properties:
        id:
          type: string
          description: "ID статуса гайда"
        name:
          type: string
          description: "Название статуса гайда"
    UserIcon:
      type: object
      properties:
        id:
          type: string
          description: "ID иконки"
        userId:
          type: string
          description: "ID пользователя"
        icon:
          type: string
          description: "Иконка пользователя"
    PaymentHistory:
      type: object
      properties:
        id:
          type: string
          description: "ID оплаты"
        userId:
          type: string
          description: "ID пользователя"
        subscriptionServiceId:
          type: string
          description: "ID сервиса-подписки"
        date:
          type: string
          format: date
          description: "Дата оплаты"
        amount:
          type: number
          description: "Стоимость"
        paymentMethod:
          type: string
          description: "Способ оплаты"
        status:
          type: string
          description: "Статус"
    Cashback:
      type: object
      properties:
        id:
          type: string
          description: "ID кешбэка"
        paymentId:
          type: string
          description: "ID оплаты"
        subscriptionServiceId:
          type: string
          description: "ID сервиса-подписки"
        date:
          type: string
          format: date
          description: "Дата начисления"
        amount:
          type: number
          description: "Сумма"
        type:
          type: string
          description: "Тип"
        status:
          type: string
          description: "Статус"
        description:
          type: string
          description: "Описание"
    SubscriptionService:
      type: object
      properties:
        id:
          type: string
          description: "ID сервиса-подписки"
        name:
          type: string
          description: "Название сервиса-подписки"
        category:
          type: string
          description: "Категория сервиса-подписки"
          $ref: '#/components/schemas/SubscriptionCategory'
        startDate:
          type: string
          format: date
          description: "Дата начала подписки"
        endDate:
          type: string
          format: date
          description: "Дата окончания подписки"
        subscriptionType:
          type: string
          description: "Тип подписки"
        cost:
          type: number
          description: "Стоимость"
    SubscriptionCategory:
      type: object
      properties:
        id:
          type: string
          description: "ID категории"
        name:
          type: string
          description: "Название категории"
        description:
          type: string
          description: "Описание"
        icon:
          type: string
          description: "Иконка категории"
    SubscriptionPayment:
      type: object
      properties:
        id:
          type: string
          description: "ID оплаты"
        userId:
          type: string
          description: "ID пользователя"
        date:
          type: string
          format: date
          description: "Дата оплаты"
        amount:
          type: number
          description: "Сумма оплаты"
    FAQ:
      type: object
      properties:
        id:
          type: string
          description: "ID вопроса"
        question: 
          type: string
          description: "текст вопроса"
        answer:
          type: string
          description: "текст ответа"
        category:
          type: string
          description: "название категории вопросов"

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/ARTDZHAGA/API_requirements_Pay2U/1.0.0